#The three different schemas for each of the main variants of TEI

all: 

download: document.teip5.xml

document.teip5.xml:
	wget --output-document=document.teip5.xml "https://raw.github.com/papyri/idp.data/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.100.xml"

validate:

build:

allclean: clean
	rm document.teip5.xml

clean:

.PHONY: all clean allclean validate download
