FILES=transform.xsl

all: 

download: ${FILES}

transform.xsl:
	wget --output-document=transform.xsl "http://www.sbl-site.org/assets/U16/U16.xsl"

validate:

build:

allclean: 
	rm -f  ${FILES}

clean:

.PHONY: all clean allclean validate download
