
download: document.teip5.xml

document.teip5.xml:
	wget --output-document=document.teip5.xml "http://tbe.kantl.be/TBE/examples/TBED00v00.htm?cocoon-view=XML"

validate:

build:

allclean: clean
	rm -f document.teip5.xml

clean:

.PHONY: all clean allclean validate download
