#The three different schemas for each of the main variants of TEI


download: document.teip5.xml

document.teip5.xml:
	wget --output-document=document.teip5.xml "http://freedict.svn.sourceforge.net/viewvc/freedict/trunk/kha-eng/kha-eng.tei"


validate:

build:

allclean: clean
	rm -f document.teip5.xml 

clean:

.PHONY: all clean allclean validate download
