FILES=p4top5.xsl

all: 

download: ${FILES}

p4top5.xsl:
	wget --output-document=p4top5.xsl "http://tei.svn.sourceforge.net/viewvc/tei/trunk/P4toP5/p4top5.xsl?revision=9184"

validate:

build:

allclean: 
	rm p4top5.xsl

clean:

.PHONY: all clean allclean validate download
