#The three different schemas for each of the main variants of TEI


download: document.teip5.xml

document.teip5.xml:
	wget --output-document=document.teip5.xml "http://www.sbl-site.org/assets/U16/U16.xml"

validate:

build:

allclean: clean
	rm -f document.teip5.xml

clean:

.PHONY: all clean allclean validate download
