#The three different schemas for each of the main variants of TEI


download: document.teip5.xml

document.teip5.xml:
	wget --output-document=document.teip5.xml "http://sarit.indology.info/downloads/ayurvedasutram.xml"

validate:

build:

allclean: clean
	rm -f document.teip5.xml

clean:

.PHONY: all clean allclean validate download
